### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by ice051128** [danieljbingham/google-image-sizer#5]
The extension doesn't work anymore.

**Comment by christopheranderton** [comment]
Stopped working yesterday for me on Chromium based browsers (Opera Dev, Chrome Stable) on macOS 10.14.6. **Firefox still works** for some reason.
I guess Google did something again.

**Comment by danieljbingham** [comment]
Thanks for letting me know, I'll look into it

**Comment by michaelzs1994** [comment]
> Thanks for letting me know, I'll look into it

doesn't work same here

**Comment by Procyon-b** [comment]
It's still working for me. I'm not using it as an extension but as a userscript (tampermonkey/chrome).
I'm using several extensions/userScripts that modify google search pages. I have encountered circumstances where google protects the page, and no userscript is allowed to run correctly. At that moment, google-image-sizer and [GIS](/devunt/make-gis-great-again) don't work. When it happens, the javascript console usually looks like this
![google-console-error](https://user-images.githubusercontent.com/40043075/69202011-8414f580-0b40-11ea-8b0e-c7e16d457d89.png)

I never see the yellow background message elsewhere.

The solution, for me, is reload the page, but sometimes clearing cookies is necessary. Note that I'm never logged in. Deleting cookies might be the only solution for identified users.

**Comment by Procyon-b** [comment]
Upon further examination, when I log in, the search page uses different styles, but apparently the userscript can run (it just fails to find the correct element).

**Comment by danieljbingham** [comment]
I've pushed a new version, and tested it both logged in and logged out - I *think* it should work now @ice051128, @christopheranderton, @michaelzs1994, @Procyon-b

**Comment by Procyon-b** [comment]
@danieljbingham Are you sure to have published the correct version of `run.user.js` ?
It doesn't fix the problem, and when I examine the code, it doesn't seem to address the problem. It's mainly an edit to replace `innerHTML` by `textContent`

**Comment by Procyon-b** [comment]
@ice051128 @christopheranderton @danieljbingham @michaelzs1994 
I've done some tests to see if I can modify the userscript to make it work with the different tags' layout and styles. While doing this I manually changed the size in the url. In the new layout (when you're logged in) the page only accepts google's standard values. No more values in megapixels.

Try it yourself. Do a search for larger images while not identified, then use the incognito mode to log in and paste the same url. You'll see that the result displayed are the one for "any size".

**Comment by christopheranderton** [comment]
For me it works on every Chromium based browser, except Opera (67.0.3554.0 Dev Channel, macOS), which is of course my main browser. Tried both the extension and running as a Userscript (not at the same time). My only theory (while this is not my area of expertise) i can see for Opera, is that they have a patch in `browser.js` to remove ”Install Chrome” on Google search pages that somehow conflicts (but the again, this is REALLY not my area of expertise). 


```
'PATCH-1269': {
        description: 'Hide Chrome ad from Google pages',
        isMatching: () => hostname.startsWith('images.google.') ||
            hostname.startsWith('www.google.'),
        applyOnDOMReady: true,
        apply: () => {
          const href =
              'https://www.google.com/url?q=/chrome/browser/desktop/';
          const res = document.evaluate(
              `//a[contains(@href, "${href}")]`, document, null,
              XPathResult.ANY_TYPE, null);
          const downloadLink = res.iterateNext();
          if (downloadLink) {
            const ad = downloadLink.closest('div[role="dialog"]');
            if (ad) {
              ad.style.display = 'none';
            }
```

**Comment by Procyon-b** [comment]
The current userscript should still work if you are not identified with google. But, once logged in, the layout of the page is internally different: HTML tags and styles are changed.
What I also noticed, which was the point of my message, is that the search requests (while identified) are also handled differently by their servers. The query parameter that handles the size of the images does not accept sizes in megapixels.
While this different layout is served when logged in, I've also seen it served for anonymous connections (when the cookies have not yet been created).

From what I can see in the pasted code, it should not prevent our userscript from working.

When you look at the source code of the google image webpage, and search for `isz_i`. Is it found? If not, it means that you are served the special version.

**Comment by christopheranderton** [comment]
Hmm. Didn't find `isz_i` in the source code. I tried to activate a flag (Use Chromium's User Agent string instead of Opera's) and restarted (cleaned cache), (still no `isz_i` in the page source), the menu still won't show. 

There is a ”Enable on search results” option on Opera Extensions (which is the same as Chrome extensions), which is turned on (else the script won't load). I use Tampermonkey as userscript manager.

I will do some digging why it differs from every other Chromium based browser.

**Comment by danieljbingham** [comment]
Apologies for the lack of replies, took some time off over the holiday period.

Been working at a version for the cases when `isz_i` isn't used, and I believe the code works, but the same problem occurs where the extension just doesn't run when the yellow WARNING message is present in the console. Still not sure how to get around that one!

**Comment by Procyon-b** [comment]
@christopheranderton  The menu won't appear if the page doesn't contain `isz_i` (it's the "new" layout). To be sure you're not logged in, you see a "sign in" blue button in the top right corner of the page.

I don't know how opera works but, try to clear all google's cookies, then reload the page.
I'll try with other user-agent string to see if the behavior changes.

@danieljbingham Apparently, even with the yellow warning message, the extension works (I've updated another userscript). The problem - if it's the same for everyone - is that, even if you make the menu appear, google image won't obey the new settings. In the new version, the server will only accept the 4 basic choices.

**Comment by Procyon-b** [comment]
Regarding the yellow warning, some scripts are failing because they try to insert html code that is prohibited/protected when the page is coded like that. But I don't thing google-image-sizer is really blocked (contrary to what I thought previously).

**Comment by christopheranderton** [comment]
@Procyon-b 
Clearing the cookies made it work (i know i should tried this first). Logged in or logged out.  
Thanks!

**Comment by Procyon-b** [comment]
This is weird. I logged in with another account, and it is served the normal layout.
I guess google is still shuffling the layouts.

**Comment by danieljbingham** [comment]
I'll try to push my fix for the second layout later today if I get chance

**Comment by Procyon-b** [comment]
@danieljbingham In you test case with the second layout, is the server actually sending really big images when you select 70mp ?

**Comment by danieljbingham** [comment]
Ok, so basically the last time I was looking at this was before Christmas, and now I'm unable to recreate the situation where `isz_i` isn't present in the page source. Last time I just had to log out, but now it seems to be working even when I'm logged out.

**Comment by danieljbingham** [comment]
Actually as soon as I post that, I get it again on Chrome's Incognito mode, so I'll play around with it again to see if it works.

**Comment by danieljbingham** [comment]
@Procyon-b @christopheranderton Just pushed a version which worked for me even when the `isz_i` wasn't present in the source code. Whether it works for people other than myself remains to be seen!

**Comment by Procyon-b** [comment]
@danieljbingham It doesn't work for me.
In the version of the page all styles are "anonymized". The onclick event does not find `hdtb-tls`.
I have made some modifications based on your code.

- after digging a bit further with "advanced search" it seems that they have restructured the query for larger sizes. Instead of `tbs=isz:20mp` it is now `tbs=isz:lt,islt:20mp`. This is the reason I couldn't make it work when I tried the old syntax. The "old" code is modified to also use this syntax.
- the html structure has also changed: not the same tags, and reversed usage (container becomes the contained, and the contained becomes the container). It was easier to user another function to handle this version of the menu.
- the currently selected value is now part of the menu, instead of checking one of our added items, it is now a matter of placing the selected value in the correct order. It means that the new function is even smaller.
- the menu is created only when it is displayed (and shared amongst several uses). I use a mutation observer to detect when the style of the "select a size" button changes (when clicked).
- I have not modified `showSizesDefault()`. This is the last thing not working in the second layout. I'll look into this if you wish.

I have tested with all the layouts available to me. All seems OK.  \o/

@christopheranderton @ice051128 @michaelzs1994  Could you check if this works for you too?

```
// ==UserScript==
// @name         Google image sizer
// @namespace    https://github.com/danieljbingham/google-image-sizer
// @version      1.0.3.4
// @description  re-implement Google Images size filter
// @author       Daniel Bingham
// @include      http*://*.google.tld/search*tbm=isch*
// @grant        none
// ==/UserScript==

(function () {

	var sz = /[?&]tbs=(?:[^&]+,)?isz(?::|%3A)([^&,]+)(?:,islt(?::|%3A)([^&,]+))?/.exec(location.search) || [];
	var sizes = [["isz_2", "2mp"], ["isz_4", "4mp"], ["isz_6", "6mp"], ["isz_8", "8mp"], ["isz_10", "10mp"],
	["isz_12", "12mp"], ["isz_15", "15mp"], ["isz_20", "20mp"], ["isz_40", "40mp"], ["isz_70", "70mp"]];

	/*
	Add sizes for one of two possibilities for the Google Images layout
	*/
	function addSizes() {
		var e;
		if (document.getElementById('isz_i')) {
			addSizesIsz();
		}
		else if (e=document.querySelector('g-card.qcTKEe')) {
			e=e.querySelector(':scope [data-index="0"]');
			const obs = new MutationObserver(function(mutL){
				for (let mut of mutL) {
					if ((mut.type=='attributes') && (mut.attributeName=='class') && mut.target.classList.contains('iWO5td')) {
						addSizesGCard();
						return;
						}
					}
				});
			obs.observe(e.parentNode, {subtree: true, attributes: true} );
			}
		else {
			addSizesOnClick();
		}
	}

	/*
	Iterate through list of image sizes and add them to the DOM (when 'isz' elements are present)
	*/
	function addSizesIsz() {
		var icon = document.getElementById("isz_i").parentNode.querySelector(':scope * + .hdtbItm:not([tabindex])');
		var parent = icon.parentNode;
		var clone, child, chkAny = false;
		for (var i = 0; i < sizes.length; i++) {
			clone = icon.cloneNode(true);
			clone.id = sizes[i][0];
			if ((sz[1]=='lt') && (sizes[i][1] == sz[2]) ) {
				clone.classList.add('hdtbSel');
				child = clone;
				chkAny = true;
				parent.previousSibling.querySelector('.mn-hd-txt').textContent = "Larger than " + sizes[i][1].toUpperCase();
				parent.previousSibling.classList.add('hdtb-tsel');
			}
			else {
				child = clone.firstChild;
				child.href = child.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)(?:,islt:([^&,]+))?/, "$1" + "isz:lt,islt:" + sizes[i][1]);
			}
			child.textContent = "Larger than " + sizes[i][1].toUpperCase();

			parent.appendChild(clone);
		}

		var fc = parent.firstElementChild;
		if (chkAny && fc.classList.contains('hdtbSel')) {
			fc.classList.remove('hdtbSel');
			child = icon.firstChild.cloneNode(true);
			child.href = child.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)/, "$1");
			child.textContent = fc.textContent;
			fc.textContent = '';
			fc.appendChild(child);
		}
	}

	function addSizesGCard() {
		var icon = document.querySelector(':scope .irf0hb > .Ix6LGe > a[href*="tbs="][href*="isz"]');
		var parent = icon.parentNode;
		if (parent.classList.contains('szDone')) return;
		parent.classList.add('szDone');
		icon.href=unescape(icon.href);
		var cur = parent.querySelector('span.MfLWbb');
		for (var i = 0; i < sizes.length; i++) {
			let clone = icon.cloneNode(true);
			clone.id = sizes[i][0];
			if ((sz[1]=='lt') && (sizes[i][1] == sz[2]) ) {
				parent.removeChild(cur);
				clone=cur;
			}
			else {
				clone.href = clone.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)(?:,islt:([^&,]+))?/, "$1" + "isz:lt,islt:" + sizes[i][1]);
				clone.firstChild.firstChild.textContent = "Larger than " + sizes[i][1].toUpperCase();
			}
			parent.appendChild(clone);
		}
	}

	/*
	When sizes nav is not already present in source code, add an event listener to add sizes when the menu is clicked
	*/
	function addSizesOnClick() {
		document.getElementById("hdtb-tls").addEventListener("click", function(){
			document.querySelectorAll('[aria-label="Size"]').item(0).addEventListener("click", function(){
				addSizesIsz();
			});
		});
	}

	/*
	Check the user is on google images
	*/
	function isImageUrl() {
		return location.href.includes("tbm=isch");
	}

	/*
	Check sizes not there already
	*/
	function needSizes() {
		var nodes = document.querySelector('[aria-label="Large"]') || document.getElementById("isz_i"); 
		if (nodes) return nodes.parentNode.childNodes.length < 6;
		else return document.querySelector('g-card.qcTKEe') && true;
	}

	/*
	Show sizes/dimensions by default instead of on hover
	*/
	function showSizesDefault() {
		var css = ".rg_anbg {display: none !important;} .rg_l:hover .rg_anbg {display: block !important;} " +
			".rg_ilmbg {display: block !important;} .rg_l:hover .rg_ilmbg {display: none !important;}";
		var style = document.createElement('style');

		if (style.styleSheet) {
			style.styleSheet.cssText = css;
		} else {
			style.appendChild(document.createTextNode(css));
		}

		document.getElementsByTagName('head')[0].appendChild(style);
	}

	//run script
	showSizesDefault();

	//somewhere: document.querySelectorAll('[role="listitem"]').item(0).addEventListener()

	var maxTries = 100;
	function chk() {
		if (!document.getElementById('isz_i') && (!document.querySelector('[aria-label="Large"]')) && (!document.querySelector('g-card.qcTKEe'))) {
			if (maxTries--) setTimeout(chk, 100);
			return;
		}
		if (needSizes()) addSizes();
	}

	if (isImageUrl()) chk();

})();
```

**Comment by Procyon-b** [comment]
I have now the correct style to invert the behavior of the size tag.
Before the final version, in the new code we could clear `aria-label` attributes of the cloned nodes. Am I wrong to think it is used by some screen readers?

**Comment by danieljbingham** [comment]
Just tried the code you posted, worked for me in whatever layout I have right now. If you want to submit a PR, I can push those changes to the chrome store - all looks good to me. And yeah, I believe `aria-label` is used for accessibility in some way (admittedly I don't know any more, but you're probably right with the screen readers).

**Comment by csaper** [comment]
@danieljbingham FYI - I, too, am experiencing issues with the extension when logged in to Google (though this seemed to have begun sometime in the last week or so). However, when accessing Image Search while in Incognito Mode (and logged out of Google), all of the size options are indeed displayed in the Size dropdown.

**INCOGNITO (LOGGED OUT) VS LOGGED IN**
![Google Image Search - Incognito vs Logged In](https://user-images.githubusercontent.com/316563/73298052-ab401100-41da-11ea-8413-8da5d690ab43.png)

_Chrome 79.0.3945.130_
_Extension version 1.0.3.4_

Any workarounds or a solution in progress?

**Comment by Procyon-b** [comment]
@csaper I'll try to reproduce your problem, and see what I can do.

**Comment by Procyon-b** [comment]
You can still try to log in with different cookies.
Google is playing with several layouts. And it is decided when it creates the cookies.
1. Clear you google.* cookies.
2. Go to google images
3. check if the the menu appears. If not, repeat 1.
4. log in
5. refresh page and check the menu. (it can still fail here)

**Comment by csaper** [comment]
@Procyon-b Thanks ;-)

Turns out the culprit was a cookie named `HSID` that Google sets on *.google.com. I have now permanently blocked the setting of that cookie via the [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg) Chrome Extension.

Appreciate the troubleshooting support.

**Comment by Procyon-b** [comment]
Don't forget about this if google ever start to misbehave.  ;)

**Comment by Procyon-b** [comment]
I've just checked something.
If I remove the HSID cookies, I'm not logged in anymore.

**[Edit]** without HSID, I'm not logged in google search, but logged in gmail

**Comment by csaper** [comment]
You are correct @Procyon-b. Seems the HSID contains some sort of account fingerprint necessary to remain logged in to Google.

I wonder if there's anything else that can be done to prevent the modification of the **Size** menu?

**Comment by Procyon-b** [comment]
Try to clear all cookie, refresh the google image page and check if the menu is correct.
Once it is correct, log in, and verify the menu again. It can work.

**Comment by Procyon-b** [comment]
You may have to refresh twice before checking the menu.

**Comment by Procyon-b** [comment]
@csaper I've found the source of the error.
Google has modified a tag in the "new" layout, and the script could not find it anymore.

Here is a revised version of the userscript. You can load it in tampermonkey (if you have it installed), or wait for @danieljbingham to update the extension.

In the meanwhile, can all of you participating in this thread test the new version and report any problem?

```
// ==UserScript==
// @name         Google image sizer
// @namespace    https://github.com/danieljbingham/google-image-sizer
// @version      1.0.3.5
// @description  re-implement Google Images size filter
// @author       Daniel Bingham
// @include      http*://*.google.tld/search*tbm=isch*
// @grant        none
// ==/UserScript==

(function () {

	var sz = /[?&]tbs=(?:[^&]+,)?isz(?::|%3A)([^&,]+)(?:,islt(?::|%3A)([^&,]+))?/.exec(location.search) || [];
	var sizes = [["isz_2", "2mp"], ["isz_4", "4mp"], ["isz_6", "6mp"], ["isz_8", "8mp"], ["isz_10", "10mp"],
	["isz_12", "12mp"], ["isz_15", "15mp"], ["isz_20", "20mp"], ["isz_40", "40mp"], ["isz_70", "70mp"]];

	/*
	Add sizes for one of two possibilities for the Google Images layout
	*/
	function addSizes() {
		var e;
		if (document.getElementById('isz_i')) {
			addSizesIsz();
		}
		else if (e=document.querySelector('.qcTKEe')) {
			e=e.querySelector(':scope [data-index="0"]');
			const obs = new MutationObserver(function(mutL){
				for (let mut of mutL) {
					if ((mut.type=='attributes') && (mut.attributeName=='class') && mut.target.classList.contains('iWO5td')) {
						addSizesGCard();
						return;
						}
					}
				});
			obs.observe(e.parentNode, {subtree: true, attributes: true} );
			}
		else {
			addSizesOnClick();
		}
	}

	/*
	Iterate through list of image sizes and add them to the DOM (when 'isz' elements are present)
	*/
	function addSizesIsz() {
		var icon = document.getElementById("isz_i").parentNode.querySelector(':scope * + .hdtbItm:not([tabindex])');
		var parent = icon.parentNode;
		var clone, child, chkAny = false;
		for (var i = 0; i < sizes.length; i++) {
			clone = icon.cloneNode(true);
			clone.id = sizes[i][0];
			if ((sz[1]=='lt') && (sizes[i][1] == sz[2]) ) {
				clone.classList.add('hdtbSel');
				child = clone;
				chkAny = true;
				parent.previousSibling.querySelector('.mn-hd-txt').textContent = "Larger than " + sizes[i][1].toUpperCase();
				parent.previousSibling.classList.add('hdtb-tsel');
			}
			else {
				child = clone.firstChild;
				child.href = child.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)(?:,islt:([^&,]+))?/, "$1" + "isz:lt,islt:" + sizes[i][1]);
			}
			child.textContent = "Larger than " + sizes[i][1].toUpperCase();

			parent.appendChild(clone);
		}

		var fc = parent.firstElementChild;
		if (chkAny && fc.classList.contains('hdtbSel')) {
			fc.classList.remove('hdtbSel');
			child = icon.firstChild.cloneNode(true);
			child.href = child.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)/, "$1");
			child.textContent = fc.textContent;
			fc.textContent = '';
			fc.appendChild(child);
		}
	}

  // alternative version of layout
	function addSizesGCard() {
		var icon = document.querySelector(':scope .irf0hb > .Ix6LGe > a[href*="tbs="][href*="isz"]');
		var parent = icon.parentNode;
		if (parent.classList.contains('szDone')) return;
		parent.classList.add('szDone');
		icon.href=unescape(icon.href);
		var cur = parent.querySelector('span.MfLWbb');
		for (var i = 0; i < sizes.length; i++) {
			let clone = icon.cloneNode(true);
			clone.id = sizes[i][0];
			if ((sz[1]=='lt') && (sizes[i][1] == sz[2]) ) {
				parent.removeChild(cur);
				clone=cur;
			}
			else {
				clone.href = clone.href.replace(/(tbs=(?:[^&]+,)?)isz(:[^&,]+)(?:,islt:([^&,]+))?/, "$1" + "isz:lt,islt:" + sizes[i][1]);
				let al = clone.firstChild.firstChild.textContent = "Larger than " + sizes[i][1].toUpperCase();
				if (clone.attributes['aria-label']) clone.attributes['aria-label'].value = al;
			}
			parent.appendChild(clone);
		}
	}

	/*
	When sizes nav is not already present in source code, add an event listener to add sizes when the menu is clicked
	*/
	function addSizesOnClick() {
		document.getElementById("hdtb-tls").addEventListener("click", function(){
			document.querySelectorAll('[aria-label="Size"]').item(0).addEventListener("click", function(){
				addSizesIsz();
			});
		});
	}

	/*
	Check the user is on google images
	*/
	function isImageUrl() {
		return location.href.includes("tbm=isch");
	}

	/*
	Check sizes not there already
	*/
	function needSizes() {
		var nodes = document.querySelector('[aria-label="Large"]') || document.getElementById("isz_i"); 
		if (nodes) return nodes.parentNode.childNodes.length < 6;
		else return document.querySelector('.qcTKEe') && true;
	}

	/*
	Show sizes/dimensions by default instead of on hover
	*/
	function showSizesDefault() {
		var css = ".rg_anbg {display: none !important;} .rg_l:hover .rg_anbg {display: block !important;} " +
			".rg_ilmbg {display: block !important;} .rg_l:hover .rg_ilmbg {display: none !important;}" +
			".h312td.RtIwE {display:block;} .isv-r.MSM1fd:hover .h312td.RtIwE {display: none;}";
		var style = document.createElement('style');

		if (style.styleSheet) {
			style.styleSheet.cssText = css;
		} else {
			style.appendChild(document.createTextNode(css));
		}

		document.getElementsByTagName('head')[0].appendChild(style);
	}

	//run script
	showSizesDefault();

	//somewhere: document.querySelectorAll('[role="listitem"]').item(0).addEventListener()

	var maxTries = 100;
	function chk() {
		if (!document.getElementById('isz_i') && (!document.querySelector('[aria-label="Large"]')) && (!document.querySelector('.qcTKEe'))) {
			if (maxTries--) setTimeout(chk, 100);
			return;
		}
		if (needSizes()) addSizes();
	}

	if (isImageUrl()) chk();

})();
```

**Comment by danieljbingham** [comment]
Apology for the late response, thank you @Procyon-b! That seems to work perfectly, so I've pushed the update
